### ISSUE TITLE
camera not showing

### ISSUE THREAD

**Issue by diadal** [diadal/barcode-scanner3#1]
please check qr code scanner capacitor 3 so far the scanning working only issue camera not showing but if you scan code it works fine

**Comment by diadal** [comment]
@tripodsgames  can you try from your side and see if you can help to fix this

**Comment by tripodsgames** [comment]
> @tripodsgames can you try from your side and see if you can help to fix this

Sure, i will check this asap.

**Comment by diadal** [comment]
every close to solution I will submit pr soon `swift` is not my line but I will try to make it work

**Comment by diadal** [comment]
@tripodsgames try check now working but only for iOS

**Comment by tripodsgames** [comment]
> @tripodsgames try check now working but only for iOS

I don't have an IPhone at the moment, sorry.
I'm going to make it work, at some level on android.

**Comment by diadal** [comment]
alright working now capacitor3 you can try to implement the android
